xinit: a little more consistency

diff --git a/xinitrc b/xinitrc
--- a/xinitrc
+++ b/xinitrc
@@ -5,28 +5,19 @@ set -eu
 xset -b
 
 # Load system xinitrc files.
-if [ -d /etc/X11/xinit/xinitrc.d ]; then
-  for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
-    [ -x "$f" ] && . "$f"
-  done
-fi
-
-if [ -d /usr/local/etc/X11/xinit/xinitrc.d ] ; then
-    for f in /usr/local/etc/X11/xinit/xinitrc.d/?*.sh ; do
-        [ -x "$f" ] && . "$f"
-    done
-fi
-unset f
-
-
-with() {
-    file="$1"
-    shift
-    if [ -r "$file" ]; then
-        $* "$file"
-    else
-        echo "xinitrc: Not found input for $* $file" > /dev/stderr
+for d in {,/usr/local}/etc/X11/xinit/xinitrc.d; do
+    if [ -d "$d" ]; then
+        for f in "$d"/?*.sh; do
+            [ -x "$f" ] && . "$f"
+        done
     fi
+done
+
+unset d f
+
+load() {
+    eval file=\${$#}
+    [ -x "$(which $1)" -a -r "$file" ] && $* || echo "$1: cannot load $file"
 }
 
 run() {
@@ -37,12 +28,14 @@ run() {
         fi
 }
 
-if [ -x "$(which xrdb 2>/dev/null)" ]; then
-    with /etc/X11/xinit/.XResources xrdb -merge
-    with /usr/local/etc/X11/xinit/.XResources xrdb -merge
-    with "$HOME/.Xdefaults" xrdb -merge
-    with "$HOME/.XResources" xrdb -merge
-fi
+load modmap "/etc/X11/xinit/.Xmodmap"
+load modmap "/usr/local/etc/X11/xinit/.Xmodmap"
+load modmap "$HOME/.Xmodmap"
+
+load xrdb -merge /etc/X11/xinit/.XResources
+load xrdb -merge /usr/local/etc/X11/xinit/.XResources
+load xrdb -merge "$HOME/.Xdefaults"
+load xrdb -merge "$HOME/.XResources"
 
 if [ -x "$(which fcitx5 2>/dev/null)" ]; then
     export XMODIFIERS="@im=fcitx"
